parameters:
- name: imageRepository
  type: string
- name: dockerfilePath
  type: string
- name: tag
  type: string

jobs:
  - job: BuildDockerImage
    displayName: Build Docker Image
    variables:
      Build_ImageRepository: ${{ parameters.imageRepository }}
      Build_Dockerfile: ${{ parameters.dockerfilePath }}
    steps:
      - task: Docker@2
        displayName: Build Docker Image
        inputs:
          command: build
          containerRegistry: 'svc_acr_connection'
          Dockerfile: $(Build_Dockerfile)
          repository: $(Build_ImageRepository)
          tags: |
            ${{ parameters.tag }}
      - task: Docker@2
        displayName: Push Docker Image
        inputs:
          command: push
          containerRegistry: 'svc_acr_connection'
          repository: $(Build_ImageRepository)
          tags: |
            ${{ parameters.tag }}
