deployconfig:
  dev:
    containerapp_name: "lmsfrontend"
    containerapp_environment: "caenv-ssvm-lms-dev"
    ingress: "external"
    target_port: 80
    min_replicas: 0
    keyvault_name: "akv-ssvm-lms-dev"
    env_vars:
      REACT_APP_BACKEND_URL: "https://lmsbackend.bluehill-eb07d9c6.centralindia.azurecontainerapps.io"
      REACT_APP_AI_QUESTIONS_API_URL: "https://qgen.bluehill-eb07d9c6.centralindia.azurecontainerapps.io"
      REACT_APP_CHATBOT_API_URL: "https://chatbot.bluehill-eb07d9c6.centralindia.azurecontainerapps.io"
    #   MONGODB_URI: "keyvaultref:https://akv-ssvm-lms-dev.vault.azure.net/secrets/MONGODB-URI/b7ab250070ef42a69e8acf0460af34a8"
    #   NODE_ENV: "development"
    #   JWT_SECRET: "keyvaultref:https://akv-ssvm-lms-dev.vault.azure.net/secrets/JWT-SECRET/7de27f91b7de4817a924c9fab2450b73"
    #   JWT_EXPIRES_IN: "24h"
    #   BCRYPT_SALT_ROUNDS: 1
    #   AZURE_STORAGE_ACCOUNT_KEY: "keyvaultref:https://akv-ssvm-lms-dev.vault.azure.net/secrets/AZURE-STORAGE-ACCOUNT-KEY/02f25cbe8de246eb895a6c25f34e1ee4"
    #   AZURE_STORAGE_ACCOUNT_NAME: "keyvaultref:https://akv-ssvm-lms-dev.vault.azure.net/secrets/STORAGE-NAME/e07fdb5daabb4fb2a851e4b7790924f1"
  uat:
    containerapp_name: "lmsfrontend"
    containerapp_environment: "caenv-ssvm-lms-uat"
    ingress: "external"
    target_port: 80
    min_replicas: 0
    keyvault_name: "akv-ssvm-lms-uat"
    env_vars:
      REACT_APP_BACKEND_URL: "https://lmsbackend.mangoplant-048dc06b.centralindia.azurecontainerapps.io"
      REACT_APP_AI_QUESTIONS_API_URL: "https://qgen.mangoplant-048dc06b.centralindia.azurecontainerapps.io"
      REACT_APP_CHATBOT_API_URL: "https://chatbot.mangoplant-048dc06b.centralindia.azurecontainerapps.io"
    #   MONGODB_URI: "keyvaultref:https://akv-ssvm-lms-uat.vault.azure.net/secrets/MONGODB-URI/b7ab250070ef42a69e8acf0460af34a8"
    #   NODE_ENV: "development"
    #   JWT_SECRET: "keyvaultref:https://akv-ssvm-lms-uat.vault.azure.net/secrets/JWT-SECRET/7de27f91b7de4817a924c9fab2450b73"
    #   JWT_EXPIRES_IN: "24h"
    #   BCRYPT_SALT_ROUNDS: 1
    #   AZURE_STORAGE_ACCOUNT_KEY: "keyvaultref:https://akv-ssvm-lms-uat.vault.azure.net/secrets/AZURE-STORAGE-ACCOUNT-KEY/02f25cbe8de246eb895a6c25f34e1ee4"
    #   AZURE_STORAGE_ACCOUNT_NAME: "keyvaultref:https://akv-ssvm-lms-uat.vault.azure.net/secrets/STORAGE-NAME/e07fdb5daabb4fb2a851e4b7790924f1"
  prd:
    containerapp_name: "lmsfrontend"
    containerapp_environment: "caenv-ssvm-lms-prd"
    ingress: "external"
    target_port: 80    
    min_replicas: 1
    keyvault_name: "akv-ssvm-lms-prd"
    env_vars:
      REACT_APP_BACKEND_URL: "https://lmsbackend.happybay-a98257cb.centralindia.azurecontainerapps.io"
      REACT_APP_AI_QUESTIONS_API_URL: "https://qgen.happybay-a98257cb.centralindia.azurecontainerapps.io"
      REACT_APP_CHATBOT_API_URL: "https://chatbot.happybay-a98257cb.centralindia.azurecontainerapps.io"
    #   MONGODB_URI: "keyvaultref:https://akv-ssvm-lms-prd.vault.azure.net/secrets/MONGODB-URI/b7ab250070ef42a69e8acf0460af34a8"
    #   NODE_ENV: "development"
    #   JWT_SECRET: "keyvaultref:https://akv-ssvm-lms-prd.vault.azure.net/secrets/JWT-SECRET/7de27f91b7de4817a924c9fab2450b73"
    #   JWT_EXPIRES_IN: "24h"
    #   BCRYPT_SALT_ROUNDS: 1
    #   AZURE_STORAGE_ACCOUNT_KEY: "keyvaultref:https://akv-ssvm-lms-prd.vault.azure.net/secrets/AZURE-STORAGE-ACCOUNT-KEY/02f25cbe8de246eb895a6c25f34e1ee4"
    #   AZURE_STORAGE_ACCOUNT_NAME: "keyvaultref:https://akv-ssvm-lms-prd.vault.azure.net/secrets/STORAGE-NAME/e07fdb5daabb4fb2a851e4b7790924f1"
